name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Change to your main branch name if different
    paths:
      - '**/*.py'       # Trigger on Python file changes
      - 'requirements.txt'  # Trigger on requirements changes
      - 'Dockerfile'    # Trigger on Dockerfile changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tiogilito21/tfgdba-app:latest
